version: "3"
services:
    database:
        image: mangoraft/mongodb-arm:latest
        environment:
         - AUTH=no
        container_name: mongo-badefass
        ports:
            - "27017:27017"
    backend:
        image:  badefass-backend
        container_name: backend
        ports:
            - "8080:8080"   
        links:
            - database
