version: "3"
services:
    database:
        image: mongo:latest
        container_name: mongo-badefass
        ports:
            - "27017:27017"
    backend:
        image:  davids23/badefass-backend:latest
        container_name: backend
        ports:
            - "8080:8080"   
        links:
            - database