version: "3"
services:
    database:
        image: mangoraft/mongodb-arm:latest
        environment:
         - AUTH=no
        container_name: badefass-mongo
        ports:
            - "27017:27017"
        volumes:
            - badefass-mongo:/data/db
        restart: always
        command: bash -c "mongod --repair && mongod"
    backend:
        build: .
        image: badefass-backend
        container_name: badefass-backend
        ports:
            - "8080:8080"   
        links:
            - database
        restart: always
volumes:
    badefass-mongo:
